version: "3.7"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./config/db.env

  vspace:
    image: digingasu/virtual-spaces:v0.10
    restart: always
    volumes:
      - vspace-data:/usr/local/tomcat/data
    env_file:
      - ./config/vspace.env
    depends_on:
      - "db"

volumes:
  db-data:
    external: true
  vspace-data:
    external: true
